[package]
name = "solana-program"
description = "Solana Program"
documentation = "https://docs.rs/solana-program"
readme = "README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = "1.75.0" # solana platform-tools rust version

[dependencies]
bincode = { workspace = true, default-features = false }
blake3 = { workspace = true, default-features = false, features = [
    "digest",
    "traits-preview",
] }
borsh = { workspace = true, default-features = false }
borsh0-10 = { git="https://github.com/fluentlabs-xyz/borsh-rs", package = "borsh", branch = "feat/svm-v0.10.3", default-features = false }
#borsh0-10 = { package = "borsh", path = "../../../borsh-rs-v0.10.3/borsh", default-features = false }
borsh0-9 = { git="https://github.com/fluentlabs-xyz/borsh-rs", package = "borsh", branch = "feat/svm-v0.9.3", default-features = false }
#borsh0-9 = { package = "borsh", path = "../../../borsh-rs-v0.9.3/borsh", default-features = false }
libsecp256k1 = { workspace = true, default-features = false, features = ["static-context"] }
bs58 = { workspace = true, default-features = false }
bv = { workspace = true, features = ["serde"], default-features = false }
bytemuck = { workspace = true, default-features = false, features = ["derive"] }
itertools = { workspace = true, default-features = false }
lazy_static = { workspace = true, default-features = false, features = ["spin_no_std"] }
log = { workspace = true, default-features = false }
memoffset = { workspace = true, default-features = false }
num-derive = { workspace = true, default-features = false }
num-traits = { workspace = true, default-features = false, features = ["i128"] }
rustversion = { workspace = true, default-features = false }
serde = { workspace = true, default-features = false, features = ["alloc"] }
serde_bytes = { workspace = true, default-features = false, features = ["alloc"]}
serde_derive = { workspace = true, default-features = false, features = [] }
serde_json = { workspace = true, default-features = false }
sha2 = { workspace = true, default-features = false }
sha3 = { workspace = true, default-features = false }
#solana-frozen-abi = { workspace = true }
#solana-frozen-abi-macro = { workspace = true }
solana-sdk-macro = { workspace = true, default-features = false }
hashbrown = { version = "0.15.1", default-features = false, features = [
    "alloc",
    "inline-more",
#    "default-hasher",
] }
#thiserror = { workspace = true }

# This is currently needed to build on-chain programs reliably.
# Borsh 0.10 may pull in hashbrown 0.13, which uses ahash 0.8, which uses
# getrandom 0.2 underneath. This explicit dependency allows for no-std if cargo
# upgrades Borsh's dependency to hashbrown 0.13.
# Remove this once borsh 0.11 or 1.0 is released, which correctly declares the
# hashbrown dependency as optional.
[target.'cfg(target_os = "solana")'.dependencies]
getrandom = { workspace = true, default-features = false, features = ["custom"] }

[target.'cfg(not(target_os = "solana"))'.dependencies]
ark-bn254 = { workspace = true, default-features = false }
ark-ec = { workspace = true, default-features = false }
ark-ff = { workspace = true, default-features = false }
ark-serialize = { workspace = true, default-features = false }
base64 = { workspace = true, default-features = false, features = [
    "alloc",
#    "std"
] }
bitflags = { workspace = true }
curve25519-dalek = { workspace = true, default-features = false, features = ["alloc"] }
itertools = { workspace = true, default-features = false }
libc = { workspace = true, default-features = false, features = ["extra_traits"] }
light-poseidon = { workspace = true, default-features = false }
num-bigint = { workspace = true, default-features = false }
rand = { workspace = true, default-features = false, features = ["alloc"] }
#tiny-bip39 = { workspace = true }
wasm-bindgen = { workspace = true, optional = true }
zeroize = { workspace = true, features = ["default", "zeroize_derive"], default-features = false }
hashbrown = { version = "0.15.1", default-features = false, features = [
    "alloc",
    "inline-more",
#    "default-hasher",
] }
spin = { version = "0.9.8", default-features = false }

[target.'cfg(not(target_os = "solana"))'.dev-dependencies]
#solana-logger = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
#console_error_panic_hook = { workspace = true }
#console_log = { workspace = true, default-features = false }
#getrandom = { workspace = true, default-features = false, features = [] }
js-sys = { workspace = true, optional = true }
hashbrown = { version = "0.15.1", default-features = false, features = [
    "alloc",
    "inline-more",
#    "default-hasher",
] }

[target.'cfg(not(target_pointer_width = "64"))'.dependencies]
#parking_lot = { workspace = true, default-features = false }

[dev-dependencies]
anyhow = { workspace = true }
array-bytes = { workspace = true }
assert_matches = { workspace = true }
serde_json = { workspace = true, default-features = false }
static_assertions = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[target.'cfg(any(unix, windows))'.build-dependencies]
cc = { workspace = true, features = ["jobserver", "parallel"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

#[lib]
#crate-type = [
#    "cdylib",
##    "rlib",
#]

[features]
default = [
#    "wbg"
    "std"
]
std = [
#    "base64/std"
]
wbg = [
    "dep:wasm-bindgen",
    "dep:js-sys",
]
